finalproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("student_management.urls")),
]

student_management/urls.py
from django.urls import path
from . import views

app_name = "student_management"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("", views.dashboard, name="dashboard"),
    path("edit-profile/", views.edit_profile, name="edit_profile"),
    path("user/", views.list_user, name="list_user"),
    path("user/add-user/", views.add_user, name="add_user"),
    path("user/delete-user/", views.delete_user, name="delete_user"),
    path("user/update-user/<str:username>", views.update_user, name="update_user"),
    path("student/", views.list_student, name="list_student"),
    path("student/add-student/", views.add_student, name="add_student"),
    path("student/delete-student/", views.delete_student, name="delete_student"),
    path(
        "student/update-student/<str:username>/",
        views.update_student,
        name="update_student",
    ),
    path(
        "student/<int:student_id>/add-lesson/",
        views.student_lesson,
        name="student_lesson",
    ),
    path("teacher/", views.list_teacher, name="list_teacher"),
    path("teacher/delete-teacher/", views.delete_teacher, name="delete_teacher"),
    path("teacher/add-teacher/", views.add_teacher, name="add_teacher"),
    path(
        "teacher/update-teacher/<int:teacher_id>/",
        views.update_teacher,
        name="update_teacher",
    ),
    path("lesson/", views.list_lesson, name="list_lesson"),
    path(
        "lesson/edit-lesson/<int:lesson_id>", views.update_lesson, name="update_lesson"
    ),
    path("lesson/add-lesson/", views.add_lesson, name="add_lesson"),
    path("lesson/delete-lesson/", views.delete_lesson, name="delete_lesson"),
    path(
        "lesson/detail-student/<int:lesson_id>/",
        views.detail_student,
        name="detail_student",
    ),
    path("lesson/add-score/<int:lesson_id>/", views.add_score, name="add_score"),
]

student_management/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    role = models.CharField(max_length=50)
    password = models.CharField(max_length=100)
    user_photo = models.ImageField(upload_to="upload/user", null=True)


class Student(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=100)
    user_photo = models.ImageField(upload_to="upload/student", null=True)


class Teacher(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=50)


class Lesson(models.Model):
    name = models.CharField(max_length=50)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    student = models.ManyToManyField(Student, through="Score")


class Score(models.Model):
    score = models.IntegerField(default=0)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)

student_management/views.py
from django.shortcuts import redirect, render
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import User, Student, Teacher, Lesson, Score
from django.db.models import Avg, Count, Max, Min


import jwt
import bcrypt
import datetime


def login(request):
    if request.method == "GET":
        return render(request, "student_management/login.html")

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if username == "root" and password == "root":
            token = encode_jwt(
                username, "root user", "rootuser", "/static/upload/root/root.png"
            )
            response = HttpResponseRedirect(reverse("student_management:dashboard"))
            response.set_cookie("access_token", token, 24 * 60 * 60)
            return response

        else:
            try:
                user = User.objects.get(username=username)
            except ObjectDoesNotExist:
                try:
                    user = Student.objects.get(username=username)
                except ObjectDoesNotExist:
                    context = {"warning": "Invalid credentials"}
                    return render(request, "student_management/login.html", context)

            if check_bcrypt(password, user.password):
                response = HttpResponseRedirect(reverse("student_management:dashboard"))
                fullname = f"{user.name} {user.surname}"

                if hasattr(user, "role"):
                    token = encode_jwt(
                        username, fullname, user.role, f"/static/{user.user_photo}"
                    )
                else:
                    token = encode_jwt(
                        username, fullname, "student", f"/static/{user.user_photo}"
                    )

                response.set_cookie("access_token", token, 24 * 60 * 60)
                return response
            else:
                context = {"warning": "Invalid credentials"}
                return render(request, "student_management/login.html", context)


def logout(request):
    response = HttpResponseRedirect(reverse("student_management:login"))
    response.delete_cookie("access_token")
    return response


def dashboard(request):
    if request.method == "GET":
        auth_user = auth(request)
        lessons = Lesson.objects.all()
        students = Student.objects.all()
        users = User.objects.all()
        teachers = Teacher.objects.all()
        avg_score = Score.objects.values("lesson__name").annotate(Avg("score"))
        max_score = Score.objects.values("lesson__name").annotate(Max("score"))
        total_student = Score.objects.values("lesson__name").annotate(Count("student"))
        max_min = Score.objects.values("lesson__name").annotate(
            Max("score"), Min("score")
        )

        # Student Dashboard
        student_lesson = ""
        student_avg = ""
        if auth_user["role"] == "student":
            student_login = Student.objects.get(username=auth_user["username"])
            student_lesson = Score.objects.filter(student=student_login.id)
            student_avg = Score.objects.filter(student=student_login.id).aggregate(
                Avg("score")
            )

        if auth_user:
            context = {
                "username": auth_user["username"],
                "fullname": auth_user["fullname"],
                "role": auth_user["role"],
                "photo": auth_user["photo"],
                "lessons": lessons,
                "students": students,
                "users": users,
                "teachers": teachers,
                "avg_score": avg_score,
                "max_score": max_score,
                "total_student": total_student,
                "max_min": max_min,
                "student_lesson": student_lesson,
                "student_avg": student_avg,
            }

            return render(request, "student_management/dashboard.html", context)
        else:
            return redirect(reverse("student_management:login"))


# ---USER---


def list_user(request):
    if request.method == "GET":
        auth_user = auth(request)
        if auth_user:
            users = User.objects.all()
            context = {
                "users": users,
                "username": auth_user["username"],
                "fullname": auth_user["fullname"],
                "role": auth_user["role"],
                "photo": auth_user["photo"],
            }
            return render(request, "student_management/user/user.html", context)
        else:
            return redirect(reverse("student_management:login"))


def add_user(request):
    auth_user = auth(request)
    if request.method == "GET":
        if auth_user:
            context = {
                "username": auth_user["username"],
                "fullname": auth_user["fullname"],
                "role": auth_user["role"],
                "photo": auth_user["photo"],
            }
            return render(request, "student_management/user/add_user.html", context)
        else:
            return redirect(reverse("student_management:login"))

    elif request.method == "POST":
        context = {
            "username": auth_user["username"],
            "fullname": auth_user["fullname"],
            "role": auth_user["role"],
            "photo": auth_user["photo"],
        }

        name = request.POST.get("name")
        surname = request.POST.get("surname")
        age = request.POST.get("age")
        gender = request.POST.get("gender")
        username = request.POST.get("username")
        role = request.POST.get("role")
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")
        user_photo = request.FILES.get("photo")

        try:
            findUsername = User.objects.get(username=username)
            context["warning"] = "Username already exist"
            return render(request, "student_management/user/add_user.html", context)

        except User.DoesNotExist:

            count = 0
            for a in username:
                if (a.isspace()) == True:
                    count += 1

            if count > 0:
                context["warning"] = "Space not allowed in username"
                return render(request, "student_management/user/add_user.html", context)

            if confirm_password == password:
                password = hash_bcrypt(password)

                user = User()
                user.name = name.lower()
                user.surname = surname.lower()
                user.age = age
                user.gender = gender
                user.username = username
                user.role = role
                user.password = password
                user.user_photo = user_photo
                user.save()

                context["success"] = "User added successfully"

                return render(request, "student_management/user/add_user.html", context)
            elif confirm_password != password:
                context["warning"] = "Password not match"

                return render(request, "student_management/user/add_user.html", context)


def delete_user(request):
    if request.method == "POST":
        userId = request.POST.get("delete_user")
        user = User.objects.get(pk=userId)
        user.delete()
        return redirect(reverse("student_management:list_user"))


def update_user(request, username):
    auth_user = auth(request)
    if request.method == "GET":
        if auth_user:
            user = User.objects.get(username=username)
            context = {
                "username": auth_user["username"],
                "fullname": auth_user["fullname"],
                "role": auth_user["role"],
                "photo": auth_user["photo"],
                "user": user,
            }
            return render(request, "student_management/user/edit_user.html", context)
        else:
            return redirect(reverse("student_management:login"))

    elif request.method == "POST":
        user = User.objects.get(username=username)
        context = {
            "username": auth_user["username"],
            "fullname": auth_user["fullname"],
            "role": auth_user["role"],
            "photo": auth_user["photo"],
            "user": user,
        }

        name = request.POST.get("name")
        surname = request.POST.get("surname")
        age = request.POST.get("age")
        gender = request.POST.get("gender")
        username = request.POST.get("username")
        role = request.POST.get("role")

        try:
            if username != user.username:
                findUsername = User.objects.get(username=username)
                context["warning"] = "Username already exist"
                return render(
                    request, "student_management/user/edit_user.html", context
                )
            User.objects.get(username="")
        except User.DoesNotExist:

            count = 0
            for a in username:
                if (a.isspace()) == True:
                    count += 1

            if count > 0:
                context["warning"] = "Space not allowed in username"
                return render(
                    request, "student_management/user/edit_user.html", context
                )

            user.name = name
            user.surname = surname
            user.age = age
            user.gender = gender
            user.username = username
            user.role = role
            user.save()
            return redirect(reverse("student_management:list_user"))


# ---Student---


def list_student(request):
    if request.method == "GET":
        auth_user = auth(request)
        if auth_user:
            students = Student.objects.all()
            context = {
                "username": auth_user["username"],

student_management/templates/student_management/teacher/add_teacher.html
{% extends 'student_management/base.html' %}
    {% block navbar %}
        {% include 'student_management/navbar.html' with active='add_teacher' %}
    {% endblock  %}

    {% block content %}
        <div class="block-header">
            <h2>ADD TEACHER</h2>
        </div>
        
        <form method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            {% if success %}
            <div class="alert bg-green alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{success}}
            </div>
            {% endif %}
            
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" name="name" required>
                                    <label class="form-label">First Name</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" name="surname" required>
                                    <label class="form-label">Surname</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="number" class="form-control" name="age" required>
                                    <label class="form-label">Age</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <span>Gender</span>
                                <input type="radio" name="gender" id="male" class="with-gap" value='male'>
                                <label for="male">Male</label>

                                <input type="radio" name="gender" id="female" class="with-gap" value="female">
                                <label for="female" class="m-l-20">Female</label>
                            </div>
                            {% if warning %}
                            <div class="alert bg-red alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>    
                                {{warning}}
                            </div>
                            {% endif %}
                            <input type="submit" class="btn btn-primary waves-effect" value="ADD">
                        </div>
                    </div>
                </div>
            </div>
        </form>
          
    {% endblock  %}

student_management/templates/student_management/teacher/edit_teacher.html
{% extends 'student_management/base.html' %}
    {% block navbar %}
        {% include 'student_management/navbar.html' with active='list_teacher' %}
    {% endblock  %}

    {% block content %}
        <div class="block-header">
            <h2>UPDATE TEACHER</h2>
        </div>
    
        <form method='POST'>
            {% csrf_token %}
            {% if success %}
            <div class="alert bg-green alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{success}}
            </div>
            {% endif %}
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="body">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" name="name" value={{teacher.name}} required>
                                    <label class="form-label">First Name</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" name="surname" value={{teacher.surname}} required>
                                    <label class="form-label">Surname</label>
                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="number" class="form-control" name="age" value={{teacher.age}} required>
                                    <label class="form-label">Age</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <span>Gender</span>
                                {% if teacher.gender == 'male' %}
                                    <input type="radio" name="gender" id="male" class="with-gap" checked="checked" value='male'>
                                {% else %}
                                    <input type="radio" name="gender" id="male" class="with-gap" value='male'>
                                {% endif %}
                                <label for="male">Male</label>

                                {% if teacher.gender == 'female' %}
                                    <input type="radio" name="gender" id="female" class="with-gap" checked="checked" value="female">
                                {% else %}
                                    <input type="radio" name="gender" id="female" class="with-gap" value="female">
                                {% endif %}
                                <label for="female" class="m-l-20">Female</label>
                            </div>
                            {% if warning %}
                            <div class="alert bg-red alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>    
                                {{warning}}
                            </div>
                            {% endif %}
                            <a style='color:black' class="btn btn-grey waves-effect" href={% url 'student_management:list_teacher' %}>CANCEL</a>
                            <input type="submit" class="btn btn-primary waves-effect" value="UPDATE">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    {% endblock  %}

student_management/templates/student_management/teacher/teacher.html
{% extends 'student_management/base.html' %}
    {% block navbar %}
        {% include 'student_management/navbar.html' with active='list_teacher' %}
    {% endblock  %}

    {% block content %}
            <div class="block-header">
                <h2>LIST OF TEACHERS</h2>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="body">
                            <div class="table-responsive js-sweetalert">
                                <table id="dataTables" class="table table-bordered table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Age</th>
                                            <th>Gender</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Name</th>
                                            <th>Age</th>
                                            <th>Gender</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for teacher in teachers %}
                                        <tr>
                                            <td>{{teacher.name|title}} {{teacher.surname|title}}</td>
                                            <td>{{teacher.age}}</td>
                                            <td>{{teacher.gender|title}}</td>
                                            <td>
                                                <a href={% url 'student_management:update_teacher' teacher.id %}>
                                                    <button type="button" class="btn btn-primary waves-effect">
                                                        <i class="material-icons">mode_edit</i>
                                                    </button>
                                                </a>
                                            </td>
                                            <td> 
                                                <button type="button" onclick='deleteTeacher({{teacher.id}},"{{teacher.name|title}} {{teacher.surname|title}}")' class="btn btn-danger waves-effect">
                                                    <i class="material-icons">delete</i>
                                                </button>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <script>
            function deleteTeacher(teacher_id, name){
                swal({
                    title: "Are you sure?",
                    text: `Once deleted ${name}, you will not be able to recover this teacher!`,
                    icon: "warning",
                    buttons: {
                        cancel: {
                            text: "Cancel",
                            value: null,
                            visible: true,
                            className: "",
                            closeModal: true,
                            },
                        confirm: {
                            text: "Delete Teacher",
                            value: true,
                            visible: true,
                            className: "",
                            closeModal: true
                        }
                    },
                    dangerMode: true,
                    })
                    .then((willDelete) => {
                    if (willDelete) {
                        swal("Poof! Teacher has been deleted!", {
                        icon: "success",
                        }).then(()=> post('/teacher/delete-teacher/', teacher_id))
                    } else {
                        swal(`Delete aborted, teacher ${name} is safe!`,{
                        icon: "error",
                        });
                    }
                    });
           }

            function post(path, value, method='POST') {
                const form = document.createElement('form');
                form.method = method;
                form.action = path;

                const hiddenField = document.createElement('input');
                hiddenField.type = 'hidden';
                hiddenField.name = 'delete_teacher';
                hiddenField.value = value;
                
                const csrfField = document.createElement('input');
                csrfField.type = 'hidden';
                csrfField.name = 'csrfmiddlewaretoken';
                csrfField.value = '{{csrf_token}}';

                form.appendChild(hiddenField);
                form.appendChild(csrfField);

                document.body.appendChild(form);
                form.submit();
            }

        </script>
    {% endblock  %}