finalproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("student_management.urls")),
]

student_management/urls.py
from django.urls import path
from . import views

app_name = "student_management"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("", views.dashboard, name="dashboard"),
    path("edit-profile/", views.edit_profile, name="edit_profile"),
    path("user/", views.list_user, name="list_user"),
    path("user/add-user/", views.add_user, name="add_user"),
    path("user/delete-user/", views.delete_user, name="delete_user"),
    path("user/update-user/<str:username>", views.update_user, name="update_user"),
    path("student/", views.list_student, name="list_student"),
    path("student/add-student/", views.add_student, name="add_student"),
    path("student/delete-student/", views.delete_student, name="delete_student"),
    path(
        "student/update-student/<str:username>/",
        views.update_student,
        name="update_student",
    ),
    path(
        "student/<int:student_id>/add-lesson/",
        views.student_lesson,
        name="student_lesson",
    ),
    path("teacher/", views.list_teacher, name="list_teacher"),
    path("teacher/delete-teacher/", views.delete_teacher, name="delete_teacher"),
    path("teacher/add-teacher/", views.add_teacher, name="add_teacher"),
    path(
        "teacher/update-teacher/<int:teacher_id>/",
        views.update_teacher,
        name="update_teacher",
    ),
    path("lesson/", views.list_lesson, name="list_lesson"),
    path(
        "lesson/edit-lesson/<int:lesson_id>", views.update_lesson, name="update_lesson"
    ),
    path("lesson/add-lesson/", views.add_lesson, name="add_lesson"),
    path("lesson/delete-lesson/", views.delete_lesson, name="delete_lesson"),
    path(
        "lesson/detail-student/<int:lesson_id>/",
        views.detail_student,
        name="detail_student",
    ),
    path("lesson/add-score/<int:lesson_id>/", views.add_score, name="add_score"),
]

student_management/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    role = models.CharField(max_length=50)
    password = models.CharField(max_length=100)
    user_photo = models.ImageField(upload_to="upload/user", null=True)


class Student(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=100)
    user_photo = models.ImageField(upload_to="upload/student", null=True)


class Teacher(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=50)


class Lesson(models.Model):
    name = models.CharField(max_length=50)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    student = models.ManyToManyField(Student, through="Score")


class Score(models.Model):
    score = models.IntegerField(default=0)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)

student_management/views.py
from django.shortcuts import redirect, render
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import User, Student, Teacher, Lesson, Score
from django.db.models import Avg, Count, Max, Min


import jwt
import bcrypt
import datetime


def login(request):
    if request.method == "GET":
        return render(request, "student_management/login.html")

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if username == "root" and password == "root":
            token = encode_jwt(
                username, "root user", "rootuser", "/static/upload/root/root.png"
            )
            response = HttpResponseRedirect(reverse("student_management:dashboard"))
            response.set_cookie("access_token", token, 24 * 60 * 60)
            return response

        else:
            try:
                user = User.objects.get(username=username)
            except ObjectDoesNotExist:
                try:
                    user = Student.objects.get(username=username)
                except ObjectDoesNotExist:
                    context = {"warning": "Invalid credentials"}
                    return render(request, "student_management/login.html", context)

            if check_bcrypt(password, user.password):
                response = HttpResponseRedirect(reverse("student_management:dashboard"))
                fullname = f"{user.name} {user.surname}"

                if hasattr(user, "role"):
                    token = encode_jwt(
                        username, fullname, user.role, f"/static/{user.user_photo}"
                    )
                else:
                    token = encode_jwt(
                        username, fullname, "student", f"/static/{user.user_photo}"
                    )

                response.set_cookie("access_token", token, 24 * 60 * 60)
                return response
            else:
                context = {"warning": "Invalid credentials"}
                return render(request, "student_management/login.html", context)


def logout(request):
    response = HttpResponseRedirect(reverse("student_management:login"))
    response.delete_cookie("access_token")
    return response


def dashboard(request):
    if request.method == "GET":
        auth_user = auth(request)
        lessons = Lesson.objects.all()
        students = Student.objects.all()
        users = User.objects.all()
        teachers = Teacher.objects.all()
        avg_score = Score.objects.values("lesson__name").annotate(Avg("score"))
        max_score = Score.objects.values("lesson__name").annotate(Max("score"))
        total_student = Score.objects.values("lesson__name").annotate(Count("student"))
        max_min = Score.objects.values("lesson__name").annotate(
            Max("score"), Min("score")
        )

        # Student Dashboard
        student_lesson = ""
        student_avg = ""
        if auth_user["role"] == "student":
            student_login = Student.objects.get(username=auth_user["username"])
            student_lesson = Score.objects.filter(student=student_login.id)
            student_avg = Score.objects.filter(student=student_login.id).aggregate(
                Avg("score")
            )

        if auth_user:
            context = {
                "username": auth_user["username"],
                "fullname": auth_user["fullname"],
                "role": auth_user["role"],
                "photo": auth_user["photo"],
                "lessons": lessons,
                "students": students,
                "users": users,
                "teachers": teachers,
                "avg_score": avg_score,
                "max_score": max_score,
                "total_student": total_student,
                "max_min": max_min,
                "student_lesson": student_lesson,
                "student_avg": student_avg,
            }

            return render(request, "student_management/dashboard.html", context)
        else:
            return redirect(reverse("student_management:login"))


# ---USER---


def list_user(request):
    if request.method == "GET":
        auth_user = auth(request)
        if auth_user:
            users = User.objects.all()
            context = {
                "users": users,
                "username": auth_user["username"],
                "fullname": auth_user["fullname"],
                "role": auth_user["role"],
                "photo": auth_user["photo"],
            }
            return render(request, "student_management/user/user.html", context)
        else:
            return redirect(reverse("student_management:login"))


def add_user(request):
    auth_user = auth(request)
    if request.method == "GET":
        if auth_user:
            context = {
                "username": auth_user["username"],
                "fullname": auth_user["fullname"],
                "role": auth_user["role"],
                "photo": auth_user["photo"],
            }
            return render(request, "student_management/user/add_user.html", context)
        else:
            return redirect(reverse("student_management:login"))

    elif request.method == "POST":
        context = {
            "username": auth_user["username"],
            "fullname": auth_user["fullname"],
            "role": auth_user["role"],
            "photo": auth_user["photo"],
        }

        name = request.POST.get("name")
        surname = request.POST.get("surname")
        age = request.POST.get("age")
        gender = request.POST.get("gender")
        username = request.POST.get("username")
        role = request.POST.get("role")
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")
        user_photo = request.FILES.get("photo")

        try:
            findUsername = User.objects.get(username=username)
            context["warning"] = "Username already exist"
            return render(request, "student_management/user/add_user.html", context)

        except User.DoesNotExist:

            count = 0
            for a in username:
                if (a.isspace()) == True:
                    count += 1

            if count > 0:
                context["warning"] = "Space not allowed in username"
                return render(request, "student_management/user/add_user.html", context)

            if confirm_password == password:
                password = hash_bcrypt(password)

                user = User()
                user.name = name.lower()
                user.surname = surname.lower()
                user.age = age
                user.gender = gender
                user.username = username
                user.role = role
                user.password = password
                user.user_photo = user_photo
                user.save()

                context["success"] = "User added successfully"

                return render(request, "student_management/user/add_user.html", context)
            elif confirm_password != password:
                context["warning"] = "Password not match"

                return render(request, "student_management/user/add_user.html", context)


def delete_user(request):
    if request.method == "POST":
        userId = request.POST.get("delete_user")
        user = User.objects.get(pk=userId)
        user.delete()
        return redirect(reverse("student_management:list_user"))


def update_user(request, username):
    auth_user = auth(request)
    if request.method == "GET":
        if auth_user:
            user = User.objects.get(username=username)
            context = {
                "username": auth_user["username"],
                "fullname": auth_user["fullname"],
                "role": auth_user["role"],
                "photo": auth_user["photo"],
                "user": user,
            }
            return render(request, "student_management/user/edit_user.html", context)
        else:
            return redirect(reverse("student_management:login"))

    elif request.method == "POST":
        user = User.objects.get(username=username)
        context = {
            "username": auth_user["username"],
            "fullname": auth_user["fullname"],
            "role": auth_user["role"],
            "photo": auth_user["photo"],
            "user": user,
        }

        name = request.POST.get("name")
        surname = request.POST.get("surname")
        age = request.POST.get("age")
        gender = request.POST.get("gender")
        username = request.POST.get("username")
        role = request.POST.get("role")

        try:
            if username != user.username:
                findUsername = User.objects.get(username=username)
                context["warning"] = "Username already exist"
                return render(
                    request, "student_management/user/edit_user.html", context
                )
            User.objects.get(username="")
        except User.DoesNotExist:

            count = 0
            for a in username:
                if (a.isspace()) == True:
                    count += 1

            if count > 0:
                context["warning"] = "Space not allowed in username"
                return render(
                    request, "student_management/user/edit_user.html", context
                )

            user.name = name
            user.surname = surname
            user.age = age
            user.gender = gender
            user.username = username
            user.role = role
            user.save()
            return redirect(reverse("student_management:list_user"))


# ---Student---


def list_student(request):
    if request.method == "GET":
        auth_user = auth(request)
        if auth_user:
            students = Student.objects.all()
            context = {
                "username": auth_user["username"],

student_management/templates/student_management/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Xiaozhuang Student Management System</title>
    <!-- Favicon-->
    <link rel="icon" href="/static/images/logo.jpg" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet"
        type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="/static/plugins/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="/static/plugins/node-waves/waves.css" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="/static/plugins/animate-css/animate.css" rel="stylesheet" />

    <!-- Morris Chart Css-->
    <link href="/static/plugins/morrisjs/morris.css" rel="stylesheet" />

    <!-- Bootstrap Select Css -->
    <link href="/static/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="/static/css/style.css" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="/static/css/themes/all-themes.css" rel="stylesheet" />

    <!-- Google Chart -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <!-- Data Tables -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
</head>

<body class="theme-indigo">
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Please wait...</p>
        </div>
    </div>

    <div class="overlay"></div>

    

    {% block navbar %}
    {% endblock  %}

    <section class="content">
        <div class="container-fluid">
            {% block content %}
            {% endblock  %}
        </div>
    </section>

    <!-- Jquery Core Js -->
    <script src="/static/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core Js -->
    <script src="/static/plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Select Plugin Js -->
    <script src="/static/plugins/bootstrap-select/js/bootstrap-select.js"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="/static/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="/static/plugins/node-waves/waves.js"></script>

    <!-- Jquery CountTo Plugin Js -->
    <script src="/static/plugins/jquery-countto/jquery.countTo.js"></script>

    <!-- Morris Plugin Js -->
    <script src="/static/plugins/raphael/raphael.min.js"></script>
    <script src="/static/plugins/morrisjs/morris.js"></script>
    
    <!-- Jquery CountTo Plugin Js -->
    <script src="/static/plugins/jquery-countto/jquery.countTo.js"></script>

    <!-- Sparkline Chart Plugin Js -->
    <script src="/static/plugins/jquery-sparkline/jquery.sparkline.js"></script>

    <!-- SweetAlert Plugin Js -->
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <!-- Demo Js -->
    <script src="/static/js/demo.js"></script>

    <!-- Datatables -->
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

    <!-- Custom Js -->
    <script src="/static/js/admin.js"></script>
    <script src="/static/js/dataTables.js"></script>

    </script>
          
</body>

</html>

student_management/templates/student_management/edit_profile.html
{% extends 'student_management/base.html' %}
    {% block navbar %}
        {% include 'student_management/navbar.html'%}
    {% endblock  %}

    {% block content %}
        <div class="block-header">
            <h2>EDIT PROFILE</h2>
        </div>
        <form method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            {% if success %}
            <div class="alert bg-green alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{success}}
            </div>
            {% endif %}
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="body">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <span>Profile Picture</span> 
                                        <input type="file" class="form-control" name="photo" accept='image/*'>
                                    </div>
                                </div>
                                <label for="">Current Password</label>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="password" class="form-control" name="old_password" required>
                                        <label class="form-label">Password</label>
                                    </div>
                                </div>
                                <label for="">New Password</label>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="password" class="form-control" name="password" required>
                                        <label class="form-label">Password</label>
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="password" class="form-control" name="confirm_password" required>
                                        <label class="form-label">Confirm Password</label>
                                    </div>
                                </div>
                                {% if warning %}
                                <div class="alert bg-red alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>    
                                    {{warning}}
                                </div>
                                {% endif %}
                                <a style='color:black' class="btn btn-grey waves-effect" href={% url 'student_management:dashboard' %}>CANCEL</a>
                                <input type="submit" class="btn btn-primary waves-effect" value="UPDATE">
                        </div>
                    </div>
                </div>
            </div>
        </form>
          
    {% endblock  %}

student_management/templates/student_management/navbar.html
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href={% url 'student_management:dashboard' %}>Xiaozhuang Student Management
                System</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if role != 'rootuser' %}
                    <li>
                        <a href={% url 'student_management:edit_profile' %} style='display:flex; align-items: center'>
                            <span style='margin-right: 5px'>Profile</span>
                            <i class="material-icons">person</i>
                        </a>
                    </li>
                {% endif %}
                <li>
                    <a href={% url 'student_management:logout' %} style='display:flex; align-items: center'>
                        <span style='margin-right: 5px'>Sign Out</span>
                        <i class="material-icons">input</i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<section>
    <aside id="leftsidebar" class="sidebar">
        <div class="user-info">
            <div class="image">
                <img src={{photo}} width="48" height="48" alt="User" />
            </div>
            <div class="info-container">
                <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{fullname|title}}
                </div>
                <div class="email">{{username}} ({{role}})</div>
            </div>
        </div>
        <div class="menu">
            <ul class="list">
                {% if active == 'dashboard' %}
                <li class='active'>
                {% else %}
                <li>
                {% endif %}
                    <a href={% url 'student_management:dashboard' %}>
                        <i class="material-icons">dashboard</i>
                        <span>DASHBOARD</span>
                    </a>
                </li>
                {% if role == 'admin' or role == 'rootuser' %}
                {% if active == 'list_user' or active == 'add_user' %}
                <li class='active'>
                {% else %}
                <li>
                {% endif %}
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">assignment_ind</i>
                        <span>USER</span>
                    </a>
                    <ul class="ml-menu">
                        {% if active == 'list_user' %}
                        <li class='active'>
                        {% else %}
                        <li>
                        {% endif %}
                            <a href={% url 'student_management:list_user' %}>List of User</a>
                        </li>
                        {% if active == 'add_user' %}
                        <li class='active'>
                        {% else %}
                        <li>
                        {% endif %}
                            <a href={% url 'student_management:add_user' %}>Add User</a>
                        </li>
                    </ul>
                </li>
                {% endif %}
                {% if role != 'student' %}
                {% if active == 'list_student' or active == 'add_student' %}
                <li class='active'>
                {% else %}
                <li>
                {% endif %}
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">school</i>
                        <span>STUDENT</span>
                    </a>
                    <ul class="ml-menu">
                        {% if active == 'list_student' %}
                        <li class='active'>
                        {% else %}
                        <li>
                        {% endif %}
                            <a href={% url 'student_management:list_student' %}>List of Student</a>
                        </li>
                        {% if active == 'add_student' %}
                        <li class='active'>
                        {% else %}
                        <li>
                        {% endif %}
                            <a href={% url 'student_management:add_student' %}>Add Student</a>
                        </li>
                    </ul>
                </li>
                {% endif %}
                {% if role != 'student' %}
                {% if active == 'list_teacher' or active == 'add_teacher' %}
                <li class='active'>
                {% else %}
                <li>
                {% endif %}
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">groups</i>
                        <span>TEACHER</span>
                    </a>
                    <ul class="ml-menu">
                        {% if active == 'list_teacher' %}
                        <li class='active'>
                        {% else %}
                        <li>
                        {% endif %}
                            <a href={% url 'student_management:list_teacher' %}>List of Teacher</a>
                        </li>
                        {% if active == 'add_teacher' %}
                        <li class='active'>
                        {% else %}
                        <li>
                        {% endif %}
                            <a href={% url 'student_management:add_teacher' %}>Add Teacher</a>
                        </li>
                    </ul>
                </li>
                {% endif %}
                {% if role != 'student' %}
                {% if active == 'list_lesson' or active == 'add_lesson' %}
                <li class='active'>
                {% else %}
                <li>
                {% endif %}
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">history_edu</i>
                        <span>LESSON</span>
                    </a>
                    <ul class="ml-menu">
                        {% if active == 'list_lesson' %}
                        <li class='active'>
                        {% else %}
                        <li>
                        {% endif %}
                            <a href={% url 'student_management:list_lesson' %}>List of Lesson</a>
                        </li>
                        {% if active == 'add_lesson' %}
                        <li class='active'>
                        {% else %}
                        <li>
                        {% endif %}
                            <a href={% url 'student_management:add_lesson' %}>Add Lesson</a>
                        </li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </aside>
</section>